name: Update VCPKG Registry

on:
  repository_dispatch:
    types: [update-event]
  workflow_dispatch:

concurrency:
  group: vcpkg
  cancel-in-progress: true

env:
  VCPKG_COMMIT_ID: 768619a21ef7fb6c5d029a7b141bb7fcef579336
  VCPKG_PORT_REPO: ${{ github.repository_owner }}

jobs:
  update-registry:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.VCPKG_HELPER_TOKEN }}

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Update Registry
        id: registry
        shell: pwsh
        run: "& ${{ github.workspace }}/.github/update-registry.ps1 ${{ github.event.client_payload.sha }}"

      - name: Check for Commit
        if: ${{ steps.registry.outputs.VCPKG_SUCCESS }} == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update registry"
          default_author: github_actions
